### ISSUE TITLE
Implement a call to WordsAPI for a random word somewhere in the app

### ISSUE THREAD

**Issue by devonbahary** [devonbahary/scholarly-v5#3]
User should receive a suggestion somewhere in the app for a word provided randomly from WordsAPI at some regular interval.

**Comment by devonbahary** [comment]
A rendered preview of the word suggestion feature.

<img width="769" alt="wireframe1" src="https://user-images.githubusercontent.com/4979092/34237207-4cbbd43a-e5b0-11e7-83e6-bc14b132db55.png">

**Comment by envoked** [comment]
Implemented in: https://github.com/devonbahary/scholarly-v5/commit/bb42dd086070f9677695832568d671527f1bb6a1
